swagger: '2.0'
info:
  version: 1.0.0
  title: LOUD
  x-ibm-name: loud
host: $(catalog.host)
basePath: /
paths:
  /loud:
    get:
      responses:
        '200':
          description: 200 OK
securityDefinitions:
  clientID:
    description: ''
    in: header
    name: X-IBM-Client-Id
    type: apiKey
security:
  - clientID: []
x-ibm-configuration:
  assembly:
    execute:
      - invoke:
          target-url: 'http://skateipsum.com/get/3/1/JSON'
          compression: false
          title: get text
      - mgw-shouty:
          version: 1.0.0
    catch: []
